#!/bin/sh
hyprctl activewindow -j | jq --raw-output .title
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -oL awk -F '>>|,' '/^activewindow>>/{if ($3 == "") {  } else if (length($3) > 60) { print substr($3, 0, 60) "..." } else { print $3 }}'
